dist: trusty
sudo: required
language: bash

before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bash
notifications:
  slack:
  rooms:
    secure: "UFnVgKWbzaAP5pRPQDfrl+FPmnfLFMiWkhZNaCGd+xxt9FJJxNWWnP7c2gAcYbZx6vmZS/LmFuqRX9VAHaC2PfEl4RbdwYyrx05Z0zLKHhRxX27w08Oh2qRE9oefveZKoCClHnZCUiLkbBs8mXhZmaHxDB2T0wJjvh2VhcJLv4wO0Wyy/TV7XAqZAz9WpWDNI++P9yv/oB4F9nBxS1lkINJnOyt8kqVrco5ILHbpimIniyEWZTEnr8abqQxTYL/Xt7sIV0HDY0IqsCbPAxkhIkszc1QdFHz+qqUXU1rFNYgnvzpbJJRL3z698Ea8YMxtb1Up1aokHTnaco9oME7O9akKde2FVMXICDQ0Vynl/coOEqa37QLiZvoysShy3uLIAArcN3z9ZjbUvlTKeE5lYe23Vz19QUMHSOSP7O4Y0RBAjcgJBUK472YGCYt/EPR1YSj46iw9hSedEnsWPHUCxwYsWDAo1oK+R8GbOduFAdtHViCHE+YlUvt0VrgxwcQhwNYe6K7o0RHlwWtSiX3VauoWS7P8fAi8mfJy7ed806wkHoXe29U7uvW8foMd6vNNj6/yVj/nH/kTyiSIq/bDKkCBOGpV60HTun203DPyuRZKcLaMT9pxWnkn77quwJIthWCjd/fSMrqNCHFaIt0xnFrYhZiOh/p/eykqcTKppVk="
